### ISSUE TITLE
error running htseq-qa -t bam alignment.bam

### ISSUE THREAD

**Issue by thkitapci** [simon-anders/htseq#6] opened 2016-04-05 23:55 UTC
I am running anaconda ->Python 2.7.11 :: Anaconda 2.5.0 (64-bit)

I installed htseq and pysam as as

conda install -c bioconda pysam
conda install -c bioconda htseq

my input file alignment.bam is a bam file generated by bwa aln and sorted with samtools sort and pcr duplicates removed with samtools rmdup

when I run
htseq-qa -t bam alignment.bam

I get this error:
..
..
..
15200000 reads processed
15400000 reads processed
15600000 reads processed
15800000 reads processed
16000000 reads processed
16200000 reads processed
16400000 reads processed
16600000 reads processed
16800000 reads processed
16930142 reads processed
Traceback (most recent call last):
File "/home/cmb-panasas2/tkitapci/libraries/lib_for_python/anaconda2_2_5_0/bin/htseq-qa", line 4, in 
import('pkg_resources').run_script('HTSeq===0.6.1p1', 'htseq-qa')
File "/home/cmb-panasas2/tkitapci/libraries/lib_for_python/anaconda2_2_5_0/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/init.py", line 726, in run_script
File "/home/cmb-panasas2/tkitapci/libraries/lib_for_python/anaconda2_2_5_0/lib/python2.7/site-packages/setuptools-20.3-py2.7.egg/pkg_resources/init.py", line 1484, in run_script
File "/auto/rcf-40/tkitapci/.local/lib/python2.7/site-packages/HTSeq-0.6.1p1-py2.7-linux-x86_64.egg/EGG-INFO/scripts/htseq-qa", line 5, in 
HTSeq.scripts.qa.main()
File "/home/rcf-40/tkitapci/.local/lib/python2.7/site-packages/HTSeq-0.6.1p1-py2.7-linux-x86_64.egg/HTSeq/scripts/qa.py", line 204, in main
norm=pyplot.normalize( 0, 1 ) )
AttributeError: 'module' object has no attribute 'normalize'

Thanks for the help!
Hamdi

**Comment by iosonofabio** [comment] 2017-02-01 17:43
duplicate of #2, will have a look thx for reporting!

**Closed by iosonofabio** 2017-02-01 17:43 UTC
