### ISSUE TITLE
Install Error on MacOS src/StepVector_wrap.cxx:3060:10: fatal error: 'stdexcept' file not found

### ISSUE THREAD

**Issue by aleighbrown** [simon-anders/htseq#78] opened 2019-04-09 09:57 UTC
Trying to install HTSeq according to the instructions. Running on Mac OS Mojave 10.14.3

Downloading the source package " HTSeq-0.11.2.tar.gz (611.2 kB)" from here https://pypi.org/project/HTSeq/#files

But getting stuck with the following error after unpacking and trying `python setup.py build` 

symlinking folders for python3
running build
running build_py
running preprocess
cythonizing
Cython version 0.29.2
SWIGging
correcting SWIG for python3
RefactoringTool: Skipping optional fixer: buffer
RefactoringTool: Skipping optional fixer: idioms
RefactoringTool: Skipping optional fixer: set_literal
RefactoringTool: Skipping optional fixer: ws_comma
RefactoringTool: No changes to python3/src/StepVector.py
RefactoringTool: Files that need to be modified:
RefactoringTool: python3/src/StepVector.py
sed: 1: "python3/src/StepVector.py": extra characters at the end of p command
SWIG not found, but transpiled files found
moving swigged .py module
done
copying HTSeq/StepVector.py -> build/lib.macosx-10.7-x86_64-3.7/HTSeq
copying HTSeq/_version.py -> build/lib.macosx-10.7-x86_64-3.7/HTSeq
running build_ext
building 'HTSeq._HTSeq' extension
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/annaleigh/anaconda3/include -arch x86_64 -I/Users/annaleigh/anaconda3/include -arch x86_64 -I/Users/annaleigh/anaconda3/lib/python3.7/site-packages/numpy/core/include -I/Users/annaleigh/anaconda3/include/python3.7m -c src/_HTSeq.c -o build/temp.macosx-10.7-x86_64-3.7/src/_HTSeq.o -w
gcc -bundle -undefined dynamic_lookup -L/Users/annaleigh/anaconda3/lib -arch x86_64 -L/Users/annaleigh/anaconda3/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.7-x86_64-3.7/src/_HTSeq.o -o build/lib.macosx-10.7-x86_64-3.7/HTSeq/_HTSeq.cpython-37m-darwin.so
building 'HTSeq._StepVector' extension
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/annaleigh/anaconda3/include -arch x86_64 -I/Users/annaleigh/anaconda3/include -arch x86_64 -I/Users/annaleigh/anaconda3/include/python3.7m -c src/StepVector_wrap.cxx -o build/temp.macosx-10.7-x86_64-3.7/src/StepVector_wrap.o -w
src/StepVector_wrap.cxx:3060:10: fatal error: 'stdexcept' file not found
#include <stdexcept>
         ^~~~~~~~~~~
1 error generated.
error: command 'gcc' failed with exit status 1

**Comment by iosonofabio** [comment] 2019-04-11 18:33
Hi,
thanks for the report. Any reason you are not using the precompiled binaries I provide for OSX? They should be downloaded if you call

```bash
pip install HTSeq
```

**Comment by aleighgreen** [comment] 2019-04-12 08:55
The reason I initially hadn't tried the `pip install HTSeq` is that it's currently described not to do that in the [Read the Docs page ](https://htseq.readthedocs.io/en/release_0.11.1/install.html#installation-on-macos-x)


Trying with pip install gives the same error fyi.

` gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/annaleigh/anaconda3/include -arch x86_64 -I/Users/annaleigh/anaconda3/include -arch x86_64 -I/Users/annaleigh/anaconda3/include/python3.7m -c src/StepVector_wrap.cxx -o build/temp.macosx-10.7-x86_64-3.7/src/StepVector_wrap.o -w
    src/StepVector_wrap.cxx:3060:10: fatal error: 'stdexcept' file not found
    #include <stdexcept>
             ^~~~~~~~~~~
    1 error generated.
    error: command 'gcc' failed with exit status 1`

Working on a debug now thanks.

**Comment by iosonofabio** [comment] 2019-04-12 16:28
Thank you for reporting, yes the docs are clearly outdated, I'll update them.

Independently of that, Mojave's youth issue still persists. It seems like the header files can be in two places depending on what chunks of Xcode you have installed, so it's a packager's nightmare. If you figure a way please report back, I'm sure other folks will appreciate :-)

**Comment by Gibbatron** [comment] 2019-04-17 13:49
Hi, I am also having this problem. I have tried downloading the source package and using 
`python setup.py build` and also the `pip install HTSeq` method. 

After looking at the comments here, I tried:
`open /Library/Developer/CommandLineTools/Packages/macOS_SDK_headers_for_macOS_10.14.pkg` and re-running the both install methods, only to get the same error message.

My error message for the source package install method:
`python setup.py build
symlinking folders for python3
running build
running build_py
running preprocess
cythonizing
Cython version 0.29.6
SWIGging
correcting SWIG for python3
RefactoringTool: Skipping optional fixer: buffer
RefactoringTool: Skipping optional fixer: idioms
RefactoringTool: Skipping optional fixer: set_literal
RefactoringTool: Skipping optional fixer: ws_comma
RefactoringTool: No changes to python3/src/StepVector.py
RefactoringTool: Files that need to be modified:
RefactoringTool: python3/src/StepVector.py
sed: 1: "python3/src/StepVector.py": extra characters at the end of p command
SWIG not found, but transpiled files found
moving swigged .py module
done
copying HTSeq/StepVector.py -> build/lib.macosx-10.7-x86_64-3.7/HTSeq
copying HTSeq/_version.py -> build/lib.macosx-10.7-x86_64-3.7/HTSeq
running build_ext
building 'HTSeq._HTSeq' extension
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/AlexGibbs/anaconda3/include -arch x86_64 -I/Users/AlexGibbs/anaconda3/include -arch x86_64 -I/Users/AlexGibbs/anaconda3/lib/python3.7/site-packages/numpy/core/include -I/Users/AlexGibbs/anaconda3/include/python3.7m -c src/_HTSeq.c -o build/temp.macosx-10.7-x86_64-3.7/src/_HTSeq.o -w
gcc -bundle -undefined dynamic_lookup -L/Users/AlexGibbs/anaconda3/lib -arch x86_64 -L/Users/AlexGibbs/anaconda3/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.7-x86_64-3.7/src/_HTSeq.o -o build/lib.macosx-10.7-x86_64-3.7/HTSeq/_HTSeq.cpython-37m-darwin.so
building 'HTSeq._StepVector' extension
gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/AlexGibbs/anaconda3/include -arch x86_64 -I/Users/AlexGibbs/anaconda3/include -arch x86_64 -I/Users/AlexGibbs/anaconda3/include/python3.7m -c src/StepVector_wrap.cxx -o build/temp.macosx-10.7-x86_64-3.7/src/StepVector_wrap.o -w
src/StepVector_wrap.cxx:3060:10: fatal error: 'stdexcept' file not found
#include <stdexcept>
         ^~~~~~~~~~~
1 error generated.
error: command 'gcc' failed with exit status 1`

The error message for the `pip install HTSeq`:
`pip install HTSeq
Collecting HTSeq
  Using cached https://files.pythonhosted.org/packages/b1/55/3612dc17fe2a85c9f0a4b98b97aa8a9850d0930e2ad89deaf9c5e1271e97/HTSeq-0.11.2.tar.gz
Requirement already satisfied: numpy in /Users/AlexGibbs/anaconda3/lib/python3.7/site-packages (from HTSeq) (1.16.2)
Requirement already satisfied: pysam>=0.9.0 in /Users/AlexGibbs/anaconda3/lib/python3.7/site-packages (from HTSeq) (0.15.2)
Building wheels for collected packages: HTSeq
  Building wheel for HTSeq (setup.py) ... error
  Complete output from command /Users/AlexGibbs/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/h4/128hzwg927d8nb8j0t8plszw0000gn/T/pip-install-0xmby568/HTSeq/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /private/var/folders/h4/128hzwg927d8nb8j0t8plszw0000gn/T/pip-wheel-fsuh13ep --python-tag cp37:
  symlinking folders for python3
  running bdist_wheel
  running build
  running build_py
  running preprocess
  cythonizing
  Cython version 0.29.6
  SWIGging
  correcting SWIG for python3
  RefactoringTool: Skipping optional fixer: buffer
  RefactoringTool: Skipping optional fixer: idioms
  RefactoringTool: Skipping optional fixer: set_literal
  RefactoringTool: Skipping optional fixer: ws_comma
  RefactoringTool: No changes to python3/src/StepVector.py
  RefactoringTool: Files that need to be modified:
  RefactoringTool: python3/src/StepVector.py
  sed: 1: "python3/src/StepVector.py": extra characters at the end of p command
  SWIG not found, but transpiled files found
  moving swigged .py module
  done
  creating build
  creating build/lib.macosx-10.7-x86_64-3.7
  creating build/lib.macosx-10.7-x86_64-3.7/HTSeq
  copying HTSeq/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/HTSeq
  copying HTSeq/_HTSeq_internal.py -> build/lib.macosx-10.7-x86_64-3.7/HTSeq
  copying HTSeq/StepVector.py -> build/lib.macosx-10.7-x86_64-3.7/HTSeq
  copying HTSeq/_version.py -> build/lib.macosx-10.7-x86_64-3.7/HTSeq
  creating build/lib.macosx-10.7-x86_64-3.7/HTSeq/scripts
  copying HTSeq/scripts/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/HTSeq/scripts
  copying HTSeq/scripts/qa.py -> build/lib.macosx-10.7-x86_64-3.7/HTSeq/scripts
  copying HTSeq/scripts/count.py -> build/lib.macosx-10.7-x86_64-3.7/HTSeq/scripts
  running build_ext
  building 'HTSeq._HTSeq' extension
  creating build/temp.macosx-10.7-x86_64-3.7
  creating build/temp.macosx-10.7-x86_64-3.7/src
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/AlexGibbs/anaconda3/include -arch x86_64 -I/Users/AlexGibbs/anaconda3/include -arch x86_64 -I/Users/AlexGibbs/anaconda3/lib/python3.7/site-packages/numpy/core/include -I/Users/AlexGibbs/anaconda3/include/python3.7m -c src/_HTSeq.c -o build/temp.macosx-10.7-x86_64-3.7/src/_HTSeq.o -w
  gcc -bundle -undefined dynamic_lookup -L/Users/AlexGibbs/anaconda3/lib -arch x86_64 -L/Users/AlexGibbs/anaconda3/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.7-x86_64-3.7/src/_HTSeq.o -o build/lib.macosx-10.7-x86_64-3.7/HTSeq/_HTSeq.cpython-37m-darwin.so
  building 'HTSeq._StepVector' extension
  gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/AlexGibbs/anaconda3/include -arch x86_64 -I/Users/AlexGibbs/anaconda3/include -arch x86_64 -I/Users/AlexGibbs/anaconda3/include/python3.7m -c src/StepVector_wrap.cxx -o build/temp.macosx-10.7-x86_64-3.7/src/StepVector_wrap.o -w
  src/StepVector_wrap.cxx:3060:10: fatal error: 'stdexcept' file not found
  #include <stdexcept>
           ^~~~~~~~~~~
  1 error generated.
  error: command 'gcc' failed with exit status 1
  
  ----------------------------------------
  Failed building wheel for HTSeq
  Running setup.py clean for HTSeq
Failed to build HTSeq
Installing collected packages: HTSeq
  Running setup.py install for HTSeq ... error
    Complete output from command /Users/AlexGibbs/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/h4/128hzwg927d8nb8j0t8plszw0000gn/T/pip-install-0xmby568/HTSeq/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/h4/128hzwg927d8nb8j0t8plszw0000gn/T/pip-record-zxzx4poy/install-record.txt --single-version-externally-managed --compile:
    symlinking folders for python3
    running install
    running build
    running build_py
    running preprocess
    cythonizing
    Cython version 0.29.6
    SWIGging
    correcting SWIG for python3
    RefactoringTool: Skipping optional fixer: buffer
    RefactoringTool: Skipping optional fixer: idioms
    RefactoringTool: Skipping optional fixer: set_literal
    RefactoringTool: Skipping optional fixer: ws_comma
    RefactoringTool: No changes to python3/src/StepVector.py
    RefactoringTool: Files that need to be modified:
    RefactoringTool: python3/src/StepVector.py
    sed: 1: "python3/src/StepVector.py": extra characters at the end of p command
    SWIG not found, but transpiled files found
    moving swigged .py module
    done
    creating build
    creating build/lib.macosx-10.7-x86_64-3.7
    creating build/lib.macosx-10.7-x86_64-3.7/HTSeq
    copying HTSeq/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/HTSeq
    copying HTSeq/_HTSeq_internal.py -> build/lib.macosx-10.7-x86_64-3.7/HTSeq
    copying HTSeq/StepVector.py -> build/lib.macosx-10.7-x86_64-3.7/HTSeq
    copying HTSeq/_version.py -> build/lib.macosx-10.7-x86_64-3.7/HTSeq
    creating build/lib.macosx-10.7-x86_64-3.7/HTSeq/scripts
    copying HTSeq/scripts/__init__.py -> build/lib.macosx-10.7-x86_64-3.7/HTSeq/scripts
    copying HTSeq/scripts/qa.py -> build/lib.macosx-10.7-x86_64-3.7/HTSeq/scripts
    copying HTSeq/scripts/count.py -> build/lib.macosx-10.7-x86_64-3.7/HTSeq/scripts
    running build_ext
    building 'HTSeq._HTSeq' extension
    creating build/temp.macosx-10.7-x86_64-3.7
    creating build/temp.macosx-10.7-x86_64-3.7/src
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/AlexGibbs/anaconda3/include -arch x86_64 -I/Users/AlexGibbs/anaconda3/include -arch x86_64 -I/Users/AlexGibbs/anaconda3/lib/python3.7/site-packages/numpy/core/include -I/Users/AlexGibbs/anaconda3/include/python3.7m -c src/_HTSeq.c -o build/temp.macosx-10.7-x86_64-3.7/src/_HTSeq.o -w
    gcc -bundle -undefined dynamic_lookup -L/Users/AlexGibbs/anaconda3/lib -arch x86_64 -L/Users/AlexGibbs/anaconda3/lib -arch x86_64 -arch x86_64 build/temp.macosx-10.7-x86_64-3.7/src/_HTSeq.o -o build/lib.macosx-10.7-x86_64-3.7/HTSeq/_HTSeq.cpython-37m-darwin.so
    building 'HTSeq._StepVector' extension
    gcc -Wno-unused-result -Wsign-compare -Wunreachable-code -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/AlexGibbs/anaconda3/include -arch x86_64 -I/Users/AlexGibbs/anaconda3/include -arch x86_64 -I/Users/AlexGibbs/anaconda3/include/python3.7m -c src/StepVector_wrap.cxx -o build/temp.macosx-10.7-x86_64-3.7/src/StepVector_wrap.o -w
    src/StepVector_wrap.cxx:3060:10: fatal error: 'stdexcept' file not found
    #include <stdexcept>
             ^~~~~~~~~~~
    1 error generated.
    error: command 'gcc' failed with exit status 1
    
    ----------------------------------------
Command "/Users/AlexGibbs/anaconda3/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/h4/128hzwg927d8nb8j0t8plszw0000gn/T/pip-install-0xmby568/HTSeq/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/var/folders/h4/128hzwg927d8nb8j0t8plszw0000gn/T/pip-record-zxzx4poy/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/h4/128hzwg927d8nb8j0t8plszw0000gn/T/pip-install-0xmby568/HTSeq/`

I am by no means an expert at any of this, so I have no idea where to go from here.
Thanks in advance,

Alex

**Comment by wjjwsl** [comment] 2019-07-23 07:37
https://github.com/simon-anders/htseq/issues/78#issuecomment-484097889
My problem is as the same as Alex's.

**Comment by Gibbatron** [comment] 2019-07-24 10:37
@wjjwsl I ended up initially following Appendix 10.2 from the HTML manual (https://bioconductor.org/packages/release/bioc/vignettes/DEXSeq/inst/doc/DEXSeq.html#8_parallelization_and_large_number_of_samples) but found this very tedious.

I then got in contact with my universities super computing team which gave me access to their supercomputer. They installed the required packages for me and I then run everything through there.

I would suggest trying to get access to a windows machine or a shell based computer to run things.

**Comment by wjjwsl** [comment] 2019-07-24 10:43
I recently find I can use crf++ by the way given by apple: http://macappstore.org/crf/
Then I can run codes like this:
`crf_train = "crf_learn -f 3 template.txt dg_train.txt dg_model"
os.system(crf_train)
crf_test = "crf_test -m dg_model dg_test.txt -o dg_result.txt"
os.system(crf_test)`
But I still cannot import crfpp. But I don't need to do this in that case.

**Comment by Gibbatron** [comment] 2019-07-24 10:55
@wjjwsl  Alternatively, you could try https://usegalaxy.org    - they have DEXseq on there, though I am not sure whether it creates your counts and prepares the annotation. Let me know if you have any luck

**Comment by jinkinson** [comment] 2019-12-31 13:59
I had this issue just now after installing htseq on my MacBook Pro with Catalina. But then when I had cd'd into the htseq folder and entered "python setup.py build" on command line, I got this error message (after a lot of tasks were apparently done successfully):

src/StepVector_wrap.cxx:3060:10: fatal error: 'stdexcept' file not found
#include <stdexcept>
         ^~~~~~~~~~~
1 error generated.
error: command '/usr/bin/clang' failed with exit status 1

**Comment by iosonofabio** [comment] 2020-03-30 07:14
This is a known issue with OSX. Apple decided to move their header files around and that causes all kinds of havoc.

OSX Mojave just became available on Travis, so I'll try to use that. Catalina is still not available there, so it's hard to make sure this works on it. If you guys have Catalina and figure out a way to fix the issue I'd be grateful.

**Comment by iosonofabio** [comment] 2020-04-01 02:23
I can reproduce this on Travis. Will try to figure out how to get around it.

**Comment by iosonofabio** [comment] 2020-04-05 04:58
Ok, this is a massive quagmire that is going to be solved robustly in Python 3.9. Everyone out there who's using Python C extensions in currently relying on hacks. I'm trying to incorporate a reasonably general solution to cover our backs until Python 3.9 is the norm.

**Comment by iosonofabio** [comment] 2020-04-05 10:37
The latest version on master installs on recent OSX versions, soon to be released on pypi as well.

Closing

**Closed by iosonofabio** 2020-04-05 10:37 UTC
